### ISSUE TITLE
Search is broken

### ISSUE THREAD

**Issue by acahn** [stormpath/stormpath-documentation#405]
The search just says "searching". Here is a URL: https://docs.stormpath.com/rest/product-guide/latest/search.html?q=white&check_keywords=yes&area=default
Options

**Comment by omgitstom** [comment]
@rdegges can you take a look at this?

**Comment by omgitstom** [comment]
Uncaught TypeError: Cannot read property 'length' of undefined
    at displayNextItem (https://docs.stormpath.com/rest/product-guide/latest/_static/searchtools.js:543:103)
    at Object.query (https://docs.stormpath.com/rest/product-guide/latest/_static/searchtools.js:574:5)
    at Object.setIndex (https://docs.stormpath.com/rest/product-guide/latest/_static/searchtools.js:362:14)
    at <anonymous>:1:8
    at p (https://docs.stormpath.com/rest/product-guide/latest/_static/jquery.js:2:523)
    at Function.globalEval (https://docs.stormpath.com/rest/product-guide/latest/_static/jquery.js:2:2595)
    at text script (https://docs.stormpath.com/rest/product-guide/latest/_static/jquery.js:4:16859)
    at Nb (https://docs.stormpath.com/rest/product-guide/latest/_static/jquery.js:4:10017)
    at A (https://docs.stormpath.com/rest/product-guide/latest/_static/jquery.js:4:13542)
    at XMLHttpRequest.<anonymous> (https://docs.stormpath.com/rest/product-guide/latest/_static/jquery.js:4:16146)

**Comment by rdegges** [comment]
Hmm. Not sure why this is error'ing out. Taking a closer look.

**Comment by rdegges** [comment]
Fixed. The searchtools.js file was the wrong version. I'm still not sure how this happened, but manually restored for now. Am doing more testing to get to the root later today.

**Comment by acahn** [comment]
I think it is broken again...

**Comment by rdegges** [comment]
After talking with @acahn this is an issue with the console guide, not this project. I'll send a PR there for a fix. @jakubswiatczak be on the lookout for a PR.

**Comment by acahn** [comment]
thanks!

**Comment by jakubvul** [comment]
Should be all good now!
